# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor_1=torch.rand(size=(7,7))
tensor_1

tensor([[0.2005, 0.2761, 0.8387, 0.9720, 0.0307, 0.1932, 0.3502],
        [0.3082, 0.9317, 0.4817, 0.8043, 0.5099, 0.8684, 0.6887],
        [0.7790, 0.7958, 0.6486, 0.3802, 0.7614, 0.8965, 0.1979],
        [0.0727, 0.7378, 0.8436, 0.7183, 0.8565, 0.4145, 0.3771],
        [0.0214, 0.4967, 0.8474, 0.8500, 0.0659, 0.8586, 0.8909],
        [0.1227, 0.0688, 0.6423, 0.0084, 0.3250, 0.5841, 0.2563],
        [0.1820, 0.9570, 0.7124, 0.5190, 0.7623, 0.7445, 0.0431]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
import torch
tensor_1=torch.rand(size=(7,7))
# Create another random tensor
tensor_2=torch.rand(size=(1,7))
# Perform matrix multiplication
tensor_2=tensor_2.T
mul=tensor_1@tensor_2
mul
#mul.shape

tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
import torch
import random
RANDOM_SEED=0

# Create two random tensors
torch.manual_seed(seed=RANDOM_SEED)
tensor_1=torch.rand(size=(7,7))
tensor_2=torch.rand(size=(1,7))
# Matrix multiply tensors
tensor_2=tensor_2.T
mul=tensor_1@tensor_2
mul,mul.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
import torch
seed=1234
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.cuda.manual_seed(seed)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
import torch
import random
#seed=1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print('Device: ',device)
# Create two random tensors on GPU
torch.manual_seed(1234)
tensor_1=torch.rand(size=(2,3))
#torch.manual_seed(1234)
tensor_2=torch.rand(size=(2,3))
tensor_on_gpu_1 = tensor_1.to(device)
tensor_on_gpu_2 = tensor_2.to(device)
tensor_on_gpu_1,tensor_on_gpu_2

Device:  cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [9]:
# Perform matmul on tensor_A and tensor_B
import torch
import random
torch.manual_seed(1234)
tensor_1=torch.rand(size=(2,3))
tensor_2=torch.rand(size=(2,3))
tensor_on_gpu_1 = tensor_1.to(device)
tensor_on_gpu_2 = tensor_2.to(device)
tensor_on_gpu_2 = tensor_on_gpu_2.T
mul=tensor_on_gpu_1@tensor_on_gpu_2
mul,mul.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
import torch
import random
torch.manual_seed(1234)
tensor_1=torch.rand(size=(2,3))
tensor_2=torch.rand(size=(2,3))
tensor_on_gpu_1 = tensor_1.to(device)
tensor_on_gpu_2 = tensor_2.to(device)
tensor_on_gpu_2 = tensor_on_gpu_2.T
mul=tensor_on_gpu_1@tensor_on_gpu_2
print('max:',mul.max())
# Find min
print('min:',mul.min())

max: tensor(0.5617, device='cuda:0')
min: tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
import torch
import random
torch.manual_seed(1234)
tensor_1=torch.rand(size=(2,3))
tensor_2=torch.rand(size=(2,3))
tensor_on_gpu_1 = tensor_1.to(device)
tensor_on_gpu_2 = tensor_2.to(device)
tensor_on_gpu_2 = tensor_on_gpu_2.T
mul=tensor_on_gpu_1@tensor_on_gpu_2
print('max:',mul.argmax())

# Find arg min
print('min:',mul.argmin())

max: tensor(3, device='cuda:0')
min: tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [17]:
# Set seed

import torch
import random
seed=7
# Create random tensor
torch.manual_seed(seed)
tensor_1=torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor_2=tensor_1.squeeze()

# Print out tensors and their shapes
print(tensor_1,tensor_1.shape)
print(tensor_2,tensor_2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
